const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sources = require("./sources");

const banner = [
  "// Generated by scripts/build.js.",
  "// Edit the functional source files under js/, then run: npm run build",
  "",
  "",
].join("\n");

const bundle = sources
  .map((source) => fs.readFileSync(path.join(root, source), "utf8").trim())
  .join("\n\n");

fs.writeFileSync(path.join(root, "js/game.js"), `${banner}${bundle}\n`, "utf8");
// Quiet under the dev server's watch loop, which rebuilds on every save.
if (!process.argv.includes("--quiet"))
  console.log(`Built js/game.js from ${sources.length} source files.`);
