const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const sources = [
  "js/core/bootstrap.js",
  "js/data/titles.js",
  "js/data/effects.js",
  "js/data/furniture.js",
  "js/data/quests.js",
  "js/data/skills.js",
  "js/data/items.js",
  "js/data/equipment.js",
  "js/core/player.js",
  "js/data/creatures.js",
  "js/systems/abilities.js",
  "js/systems/effectors.js",
  "js/world/areas.js",
  "js/world/sectors.js",
  "js/systems/containers.js",
  "js/systems/crafting.js",
  "js/systems/actions.js",
  "js/ui/interface.js",
  "js/world/locations.js",
  "js/systems/simulation.js",
  "js/systems/planner.js",
  "js/ui/map-and-mastery.js",
  "js/utils/random.js",
  "js/utils/encoding.js",
];

const banner = [
  "// Generated by scripts/build.js.",
  "// Edit the functional source files under js/, then run: npm run build",
  "",
  "",
].join("\n");

const bundle = sources
  .map((source) => fs.readFileSync(path.join(root, source), "utf8").trim())
  .join("\n\n");

fs.writeFileSync(path.join(root, "js/game.js"), `${banner}${bundle}\n`, "utf8");
console.log(`Built js/game.js from ${sources.length} source files.`);
